version: "3.9"

services:
  bootnode:
    image: ethnet/tools
    container_name: bootnone
    entrypoint: /usr/bin/bootnode -discv5-port 39000 -external-ip 172.99.1.1 -private 37871f094f89fc95599e73d72d3008c828bb76d0864759011fa14dbaf6cf3c06 -fork-version 20000089
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    networks:
      meta:
        ipv4_address: 172.99.1.1
  
  execution:
    image: ethnet/tools
    container_name: execute
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ./config:/root/config
    networks:
      - meta

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - bootnode
      - execution
    networks:
      - meta
networks:
  meta:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16
