version: "3.9"

services:
  execution:
    image: ethnet/tools
    container_name: execute
    entrypoint: /usr/local/bin/execution.sh
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    ports:
      - "8551:8551"
    volumes:
      - ./config:/root/config
    networks:
      - meta

  beacon-1:
    image: ethnet/tools
    container_name: beacon-1
    entrypoint: /usr/local/bin/beacon-node.sh
    environment:
      - BOOTNODE=${BOOTNODE_ENR}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 100
        window: 120s
    volumes:
      - ./config:/root/config
    depends_on:
      - execution
    networks:
      - meta

networks:
  meta:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16
